#ifndef OXS_CONFIG_ADVANCED_h
#define OXS_CONFIG_ADVANCED_h

#define PIN_SERIALTX 4

#define         DATA_ID_VARIO  0x00
#define         DATA_ID_FLVSS  0xA1
#define         DATA_ID_FAS    0x22
#define         DATA_ID_GPS    0x83
#define         DATA_ID_RPM    0xE4
#define         DATA_ID_ACC    0x67
#define         DATA_ID_TX     0x0D

#define FILL_TEST_1_2_3_WITH_LINEAR_ACC

#define FILL_TEST_1_2_WITH_VSPEED_AND_ALT_FROM_SECOND_VARIO

#define FILL_TEST_1_WITH_DTE

#define FILL_TEST_2_WITH_PPM_AIRSPEED_COMPENSATION

#define FILL_TEST_1_WITH_YAWRATE

#define FILL_TEST1_WITH_HEADING_FROM_MAGNETOMETER

#define FILL_TEST_1_2_3_WITH_FLOW_SENSOR_CONSUMPTION

#define FILL_TEST1_WITH_GPS_NUMBER_OF_SAT

#define FILL_TEST2_WITH_GPS_HDOP

#endif
