#ifndef OXS_CONFIG_BASIC_h
#define OXS_CONFIG_BASIC_h


#define PROTOCOL FRSKY_SPORT

#define VFAS_SOURCE VOLT_1
#define FUEL_SOURCE VOLT_2
#define A3_SOURCE VOLT_3
#define A4_SOURCE VOLT_4
#define ACCX_SOURCE VOLT_5
#define ACCY_SOURCE VOLT_6
#define ACCZ_SOURCE TEST_1
#define T1_SOURCE TEST_2
#define T2_SOURCE TEST_3
#define FIRST_BARO_SENSOR_USE MS5611
#define VSPEED_SOURCE FIRST_BARO
#define AIRSPEED_SENSOR_USE MS4525

#define ARDUINO_MEASURES_VOLTAGES   YES
#define NUMBEROFCELLS 2

#define ARDUINO_MEASURES_A_CURRENT YES

#define AN_ADS1115_IS_CONNECTED YES

#define CALCULATE_RPM YES

#define SAVE_TO_EEPROM NO

#define A_GPS_IS_CONNECTED YES

#define A_MPU6050_IS_CONNECTED YES

#define CALCULATE_YAW_WITH_HMC5883 YES

#define A_FLOW_SENSOR_IS_CONNECTED   YES

#define A_LOCATOR_IS_CONNECTED   YES

#endif
